# Dockerfile.watcher
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy watcher script
COPY ./app /app

# Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Run watcher
CMD ["python", "watcher.py"]
